# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*    # chỉ trigger khi có thay đổi trong thư mục result

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '00f95541-34f4-46c8-81bc-fb3b7dfc34e0'
  imageRepository: 'votingapp'
  containerRegistry: 'tofuvotingappacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'votingApp-Agent'   # tên agent pool đã tạo ở Step 4

stages:
- stage: Build
  displayName: Build the Voting App
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'tofuVotingAppACR'
        repository: 'votingApp/result'
        command: 'build'
        dockerfile: 'result/Dockerfile'
        tags: |
          $(tag)
- stage: Push
  displayName: Push the Voting App
  jobs:
  - job: Push
    displayName: Pushing the voting App
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'tofuVotingAppACR'
        repository: 'votingApp/result'
        command: 'push'
        tags: |
          $(tag)
