defaultRules:
  create: true

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 15s
    evaluationInterval: 15s
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1536Mi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 31300
  adminUser: admin
  adminPassword: "ChangeMe-Grafana-Admin-2026!"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
  config:
    global:
      resolve_timeout: 2m
    route:
      receiver: "null"
      group_by:
        - alertname
        - namespace
        - severity
      group_wait: 15s
      group_interval: 30s
      repeat_interval: 5m
      routes:
        - matchers:
            - severity="critical"
          receiver: "null"
        - matchers:
            - severity="warning"
          receiver: "null"
    receivers:
      - name: "null"

"prometheus-node-exporter":
  enabled: true

"kube-state-metrics":
  enabled: true

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
