apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vote-monitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: vote
  endpoints:
    - port: vote-service
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: result-monitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: result
  endpoints:
    - port: result-service
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-monitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: worker
      metrics: enabled
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
