apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - image: tofuvotingappacr.azurecr.io/votingapp/vote:72
        name: vote
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: vote
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 512Mi
