apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
    metrics: enabled
  name: worker-metrics
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
  selector:
    app: worker
